### ISSUE TITLE
Is it possible to increase followers and leaders?

### ISSUE THREAD

**Issue by serapergun** [tkn-tub/serpentine-env#10]
Hi,
In serpentine-env, there is just one follower and one leader.
Is it possible to increase their numbers?
For example: 5 leaders-5 followers or 1 leader-5 followers.

If so, can it be done just changing on serpentine.rou.xml?

Regards,

**Comment by dbuse** [comment]
hi @serapergun 

You can modify the traffic by adjusting the `serpentine.rou.xml` file, yes. 
However, every vehicle id can only be used once. And the C++ implementation uses the vehice id to identify vehicles. Also, for the application of the serpentine-env, only one leader and follower are of interest. You could however extend it to have multiple *pairs* of leaders and followers. Though that would need some futher extensions to make sure those pairs correctly interact with each other.

**Comment by serapergun** [comment]
@dbuse Thank you, I got the basic issue.
Regards,
