### ISSUE TITLE
Problem while runing 'snamke -jall' for installing

### ISSUE THREAD

**Issue by anjackq** [tkn-tub/serpentine-env#12]
`~/Desktop/serpentine-env$ snakemake -jall

Building DAG of jobs...
Using shell: /usr/bin/bash
Provided cores: 4
Rules claiming more threads will be scaled down.
Job stats:
job                count    min threads    max threads
---------------  -------  -------------  -------------
all                    1              1              1
build                  2              4              4
build_veins            1              4              4
build_veins_vlc        2              4              4
total                  6              1              4

Select jobs to execute...

[Wed Sep 21 10:25:07 2022]
rule build_veins_vlc:
    input: lib/veins/src/libveins.so, lib/veins-vlc/src/Makefile
    output: lib/veins-vlc/src/libveins-vlc.so
    jobid: 10
    reason: Missing output files: lib/veins-vlc/src/libveins-vlc.so
    wildcards: dbg=
    threads: 4
    resources: tmpdir=/tmp

make: Entering directory '/home/anjie/Desktop/serpentine-env/lib/veins-vlc/src'
MSGC: veins-vlc/messages/AirFrameVlc.msg
MSGC: veins-vlc/messages/VlcMessage.msg
veins-vlc/messages/VlcMessage.msg:25: Error: Type declarations are not needed with imports, try invoking the message compiler in legacy (4.x) mode using the --msg4 option
veins-vlc/messages/VlcMessage.msg:27: Error: 'VlcMessage': unknown base class 'veins::BaseFrame1609_4'
veins-vlc/messages/VlcMessage.msg:27: Error: VlcMessage: base class is not a message (must be derived from omnetpp::cMessage)
opp_msgtool: error in 1 file(s)
veins-vlc/messages/AirFrameVlc.msg:28: Error: Type declarations are not needed with imports, try invoking the message compiler in legacy (4.x) mode using the --msg4 option
veins-vlc/messages/AirFrameVlc.msg:30: Error: 'AirFrameVlc': unknown base class 'AirFrame'
veins-vlc/messages/AirFrameVlc.msg:30: Error: AirFrameVlc: base class is not a message (must be derived from omnetpp::cMessage)
make: *** [Makefile:146: veins-vlc/messages/VlcMessage_m.h] Error 1
make: *** Waiting for unfinished jobs....
opp_msgtool: error in 1 file(s)
make: *** [Makefile:146: veins-vlc/messages/AirFrameVlc_m.h] Error 1
make: Leaving directory '/home/anjie/Desktop/serpentine-env/lib/veins-vlc/src'
[Wed Sep 21 10:25:07 2022]
Error in rule build_veins_vlc:
    jobid: 10
    output: lib/veins-vlc/src/libveins-vlc.so
    shell:
        make -j4 -C lib/veins-vlc/src MODE=release
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-09-21T102507.149167.snakemake.log
`

**Comment by dbuse** [comment]
Hi @anjackq 

it looks like you are using OMNeT++ Version 6 or later. For Veins-Gym's Serpentine-Env, we still use the (old) message definition. So the easiest fix would be to switch to OMNeT++ v5.6
