### ISSUE TITLE
pip install veins_gym snakemake

### ISSUE THREAD

**Issue by mohammadpasha** [tkn-tub/serpentine-env#2]
I am trying to install veins_gym

veins:~% pip install veins_gym snakemake
Collecting veins_gym
  Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f7c44fb3c50>: Failed to establish a new connection: [Errno -2] Name or service not known',)': /simple/veins-gym/

Is there anything i am missing. I am using instant veins. I am working behind a proxy

Thanks

**Comment by dbuse** [comment]
Hi @mohammadpasha 

This sounds like a problem with your proxy configuration to me. `pip install` directly contacts <https://pypi.org/>, so this is nothing specific to veins_gym. At least I would expect that other packet installations like, e.g.,  `pip install requests` would fail with the same message. Maybe searching for using pip with a proxy can help you.

Best,
Dominik
