### ISSUE TITLE
snakemake -jall produces an error

### ISSUE THREAD

**Issue by Anas-1998** [tkn-tub/serpentine-env#3]
Hello,
I was trying to follow the tutorial you presented here and the in first line where I want to compile the cloned env, it produces this error in the console
Please let me know what I need to do.
Thank you in advance
Error output:
Error in rule build_veins:
    jobid: 2
    output: lib/veins/src/libveins_dbg.so
    shell:
        make -j24 -C lib/veins/src MODE=debug
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
The input used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-input-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-input-changes)'.
Complete log: /home/dlsystem/serpentine-env/.snakemake/log/2022-03-09T022605.762192.snakemake.log

Full output:
Building DAG of jobs...
The input used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-input-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-input-changes)'.
Using shell: /usr/bin/bash
Provided cores: 24
Rules claiming more threads will be scaled down.
Job stats:
job                count    min threads    max threads
---------------  -------  -------------  -------------
all                    1              1              1
build                  2             24             24
build_veins            2             24             24
build_veins_vlc        2             24             24
configure_veins        1              1              1
total                  8              1             24

Select jobs to execute...

[Wed Mar  9 02:26:05 2022]
rule configure_veins:
    input: lib/veins/src/veins/base/messages/MacPkt.msg, lib/veins/src/veins/base/messages/AirFrame.msg, lib/veins/src/veins/base/messages/BorderMsg.msg, lib/veins/src/veins/modules/messages/PhyControlMessage.msg, lib/veins/src/veins/modules/messages/DemoSafetyMessage.msg, lib/veins/src/veins/modules/messages/Mac80211Pkt.msg, lib/veins/src/veins/modules/messages/TraCITrafficLightMessage.msg, lib/veins/src/veins/modules/messages/Mac80211Ack.msg, lib/veins/src/veins/modules/messages/AckTimeOutMessage.msg, lib/veins/src/veins/modules/messages/BaseFrame1609_4.msg, lib/veins/src/veins/modules/messages/DemoServiceAdvertisement.msg, lib/veins/src/veins/modules/messages/AirFrame11p.msg, lib/veins/src/veins/modules/application/traci/TraCIDemo11pMessage.msg, lib/veins/src/veins/base/utils/NetwToMacControlInfo.cc, lib/veins/src/veins/base/utils/Heading.cc, lib/veins/src/veins/base/utils/SimpleAddress.cc, lib/veins/src/veins/base/utils/winsupport.cc, lib/veins/src/veins/base/utils/Coord.cc, lib/veins/src/veins/base/messages/MacPkt_m.cc, lib/veins/src/veins/base/messages/BorderMsg_m.cc, lib/veins/src/veins/base/messages/AirFrame_m.cc, lib/veins/src/veins/base/connectionManager/NicEntryDebug.cc, lib/veins/src/veins/base/connectionManager/NicEntryDirect.cc, lib/veins/src/veins/base/connectionManager/ChannelAccess.cc, lib/veins/src/veins/base/connectionManager/BaseConnectionManager.cc, lib/veins/src/veins/base/connectionManager/ConnectionManager.cc, lib/veins/src/veins/base/toolbox/SignalUtils.cc, lib/veins/src/veins/base/toolbox/Signal.cc, lib/veins/src/veins/base/toolbox/Spectrum.cc, lib/veins/src/veins/base/modules/BaseMacLayer.cc, lib/veins/src/veins/base/modules/BatteryAccess.cc, lib/veins/src/veins/base/modules/BaseWorldUtility.cc, lib/veins/src/veins/base/modules/BaseApplLayer.cc, lib/veins/src/veins/base/modules/BaseLayer.cc, lib/veins/src/veins/base/modules/BaseModule.cc, lib/veins/src/veins/base/modules/BaseMobility.cc, lib/veins/src/veins/base/modules/BaseBattery.cc, lib/veins/src/veins/base/phyLayer/PhyUtils.cc, lib/veins/src/veins/base/phyLayer/Decider.cc, lib/veins/src/veins/base/phyLayer/BasePhyLayer.cc, lib/veins/src/veins/base/phyLayer/Antenna.cc, lib/veins/src/veins/base/phyLayer/BaseDecider.cc, lib/veins/src/veins/base/phyLayer/ChannelInfo.cc, lib/veins/src/veins/modules/world/traci/trafficLight/TraCITrafficLightProgram.cc, lib/veins/src/veins/modules/world/traci/trafficLight/TraCITrafficLightInterface.cc, lib/veins/src/veins/modules/world/traci/trafficLight/logics/TraCITrafficLightAbstractLogic.cc, lib/veins/src/veins/modules/world/traci/trafficLight/logics/TraCITrafficLightSimpleLogic.cc, lib/veins/src/veins/modules/world/annotations/AnnotationManager.cc, lib/veins/src/veins/modules/world/annotations/AnnotationDummy.cc, lib/veins/src/veins/modules/mac/ieee80211p/Mac1609_4.cc, lib/veins/src/veins/modules/obstacle/MobileHostObstacle.cc, lib/veins/src/veins/modules/obstacle/ObstacleControl.cc, lib/veins/src/veins/modules/obstacle/Obstacle.cc, lib/veins/src/veins/modules/obstacle/VehicleObstacleControl.cc, lib/veins/src/veins/modules/utility/BBoxLookup.cc, lib/veins/src/veins/modules/utility/TimerManager.cc, lib/veins/src/veins/modules/utility/HasLogProxy.cc, lib/veins/src/veins/modules/phy/Decider80211p.cc, lib/veins/src/veins/modules/phy/SampledAntenna1D.cc, lib/veins/src/veins/modules/phy/NistErrorRate.cc, lib/veins/src/veins/modules/phy/PhyLayer80211p.cc, lib/veins/src/veins/modules/messages/BaseFrame1609_4_m.cc, lib/veins/src/veins/modules/messages/PhyControlMessage_m.cc, lib/veins/src/veins/modules/messages/AckTimeOutMessage_m.cc, lib/veins/src/veins/modules/messages/Mac80211Ack_m.cc, lib/veins/src/veins/modules/messages/AirFrame11p_m.cc, lib/veins/src/veins/modules/messages/DemoSafetyMessage_m.cc, lib/veins/src/veins/modules/messages/Mac80211Pkt_m.cc, lib/veins/src/veins/modules/messages/DemoServiceAdvertisement_m.cc, lib/veins/src/veins/modules/messages/TraCITrafficLightMessage_m.cc, lib/veins/src/veins/modules/application/traci/TraCIDemoRSU11p.cc, lib/veins/src/veins/modules/application/traci/TraCIDemo11pMessage_m.cc, lib/veins/src/veins/modules/application/traci/TraCIDemo11p.cc, lib/veins/src/veins/modules/application/traci/MyVeinsApp.cc, lib/veins/src/veins/modules/application/ieee80211p/DemoBaseApplLayer.cc, lib/veins/src/veins/modules/analogueModel/NakagamiFading.cc, lib/veins/src/veins/modules/analogueModel/VehicleObstacleShadowing.cc, lib/veins/src/veins/modules/analogueModel/SimplePathlossModel.cc, lib/veins/src/veins/modules/analogueModel/TwoRayInterferenceModel.cc, lib/veins/src/veins/modules/analogueModel/SimpleObstacleShadowing.cc, lib/veins/src/veins/modules/analogueModel/PERModel.cc, lib/veins/src/veins/modules/analogueModel/BreakpointPathlossModel.cc, lib/veins/src/veins/modules/mobility/LinearMobility.cc, lib/veins/src/veins/modules/mobility/traci/TraCIBuffer.cc, lib/veins/src/veins/modules/mobility/traci/TraCICoordinateTransformation.cc, lib/veins/src/veins/modules/mobility/traci/TraCILauncher.cc, lib/veins/src/veins/modules/mobility/traci/TraCIRegionOfInterest.cc, lib/veins/src/veins/modules/mobility/traci/TraCIMobility.cc, lib/veins/src/veins/modules/mobility/traci/TraCIScreenRecorder.cc, lib/veins/src/veins/modules/mobility/traci/TraCIVehicleInserter.cc, lib/veins/src/veins/modules/mobility/traci/TraCIColor.cc, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.cc, lib/veins/src/veins/modules/mobility/traci/TraCICommandInterface.cc, lib/veins/src/veins/modules/mobility/traci/TraCIConnection.cc, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManager.cc, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManagerLaunchd.cc, lib/veins/src/veins/veins.h, lib/veins/src/veins/base/utils/HostState.h, lib/veins/src/veins/base/utils/PassedMessage.h, lib/veins/src/veins/base/utils/NetwToMacControlInfo.h, lib/veins/src/veins/base/utils/Coord.h, lib/veins/src/veins/base/utils/MacToNetwControlInfo.h, lib/veins/src/veins/base/utils/EnumBitset.h, lib/veins/src/veins/base/utils/SimpleAddress.h, lib/veins/src/veins/base/utils/AntennaPosition.h, lib/veins/src/veins/base/utils/POA.h, lib/veins/src/veins/base/utils/FindModule.h, lib/veins/src/veins/base/utils/Heading.h, lib/veins/src/veins/base/utils/Move.h, lib/veins/src/veins/base/utils/winsupport.h, lib/veins/src/veins/base/utils/FWMath.h, lib/veins/src/veins/base/messages/BorderMsg_m.h, lib/veins/src/veins/base/messages/MacPkt_m.h, lib/veins/src/veins/base/messages/AirFrame_m.h, lib/veins/src/veins/base/connectionManager/NicEntry.h, lib/veins/src/veins/base/connectionManager/ConnectionManager.h, lib/veins/src/veins/base/connectionManager/BaseConnectionManager.h, lib/veins/src/veins/base/connectionManager/ChannelAccess.h, lib/veins/src/veins/base/connectionManager/NicEntryDebug.h, lib/veins/src/veins/base/connectionManager/NicEntryDirect.h, lib/veins/src/veins/base/toolbox/SignalUtils.h, lib/veins/src/veins/base/toolbox/Signal.h, lib/veins/src/veins/base/toolbox/Spectrum.h, lib/veins/src/veins/base/modules/AddressingInterface.h, lib/veins/src/veins/base/modules/BaseBattery.h, lib/veins/src/veins/base/modules/BaseMacLayer.h, lib/veins/src/veins/base/modules/BaseWorldUtility.h, lib/veins/src/veins/base/modules/BatteryAccess.h, lib/veins/src/veins/base/modules/BaseApplLayer.h, lib/veins/src/veins/base/modules/BaseLayer.h, lib/veins/src/veins/base/modules/BaseModule.h, lib/veins/src/veins/base/modules/BaseMobility.h, lib/veins/src/veins/base/phyLayer/BaseDecider.h, lib/veins/src/veins/base/phyLayer/BasePhyLayer.h, lib/veins/src/veins/base/phyLayer/AnalogueModel.h, lib/veins/src/veins/base/phyLayer/Decider.h, lib/veins/src/veins/base/phyLayer/PhyToMacControlInfo.h, lib/veins/src/veins/base/phyLayer/DeciderToPhyInterface.h, lib/veins/src/veins/base/phyLayer/Antenna.h, lib/veins/src/veins/base/phyLayer/PhyUtils.h, lib/veins/src/veins/base/phyLayer/ChannelInfo.h, lib/veins/src/veins/base/phyLayer/MacToPhyInterface.h, lib/veins/src/veins/modules/world/traci/trafficLight/TraCITrafficLightInterface.h, lib/veins/src/veins/modules/world/traci/trafficLight/TraCITrafficLightProgram.h, lib/veins/src/veins/modules/world/traci/trafficLight/logics/TraCITrafficLightSimpleLogic.h, lib/veins/src/veins/modules/world/traci/trafficLight/logics/TraCITrafficLightAbstractLogic.h, lib/veins/src/veins/modules/world/annotations/AnnotationDummy.h, lib/veins/src/veins/modules/world/annotations/AnnotationManager.h, lib/veins/src/veins/modules/mac/ieee80211p/Mac80211pToPhy11pInterface.h, lib/veins/src/veins/modules/mac/ieee80211p/Mac1609_4.h, lib/veins/src/veins/modules/mac/ieee80211p/DemoBaseApplLayerToMac1609_4Interface.h, lib/veins/src/veins/modules/obstacle/MobileHostObstacle.h, lib/veins/src/veins/modules/obstacle/ObstacleControl.h, lib/veins/src/veins/modules/obstacle/Obstacle.h, lib/veins/src/veins/modules/obstacle/VehicleObstacleControl.h, lib/veins/src/veins/modules/utility/Consts80211p.h, lib/veins/src/veins/modules/utility/MacToPhyControlInfo11p.h, lib/veins/src/veins/modules/utility/BBoxLookup.h, lib/veins/src/veins/modules/utility/HasLogProxy.h, lib/veins/src/veins/modules/utility/TimerManager.h, lib/veins/src/veins/modules/utility/ConstsPhy.h, lib/veins/src/veins/modules/utility/SignalManager.h, lib/veins/src/veins/modules/phy/DeciderResult80211.h, lib/veins/src/veins/modules/phy/Decider80211pToPhy80211pInterface.h, lib/veins/src/veins/modules/phy/SampledAntenna1D.h, lib/veins/src/veins/modules/phy/PhyLayer80211p.h, lib/veins/src/veins/modules/phy/Decider80211p.h, lib/veins/src/veins/modules/phy/NistErrorRate.h, lib/veins/src/veins/modules/messages/Mac80211Pkt_m.h, lib/veins/src/veins/modules/messages/TraCITrafficLightMessage_m.h, lib/veins/src/veins/modules/messages/Mac80211Ack_m.h, lib/veins/src/veins/modules/messages/AckTimeOutMessage_m.h, lib/veins/src/veins/modules/messages/DemoSafetyMessage_m.h, lib/veins/src/veins/modules/messages/BaseFrame1609_4_m.h, lib/veins/src/veins/modules/messages/AirFrame11p_m.h, lib/veins/src/veins/modules/messages/PhyControlMessage_m.h, lib/veins/src/veins/modules/messages/DemoServiceAdvertisement_m.h, lib/veins/src/veins/modules/application/traci/TraCIDemo11pMessage_m.h, lib/veins/src/veins/modules/application/traci/TraCIDemo11p.h, lib/veins/src/veins/modules/application/traci/MyVeinsApp.h, lib/veins/src/veins/modules/application/traci/TraCIDemoRSU11p.h, lib/veins/src/veins/modules/application/ieee80211p/DemoBaseApplLayer.h, lib/veins/src/veins/modules/analogueModel/PERModel.h, lib/veins/src/veins/modules/analogueModel/TwoRayInterferenceModel.h, lib/veins/src/veins/modules/analogueModel/VehicleObstacleShadowing.h, lib/veins/src/veins/modules/analogueModel/NakagamiFading.h, lib/veins/src/veins/modules/analogueModel/SimplePathlossModel.h, lib/veins/src/veins/modules/analogueModel/SimpleObstacleShadowing.h, lib/veins/src/veins/modules/analogueModel/BreakpointPathlossModel.h, lib/veins/src/veins/modules/mobility/LinearMobility.h, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManagerForker.h, lib/veins/src/veins/modules/mobility/traci/TraCIMobility.h, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManager.h, lib/veins/src/veins/modules/mobility/traci/TraCIVehicleInserter.h, lib/veins/src/veins/modules/mobility/traci/TraCIConstants.h, lib/veins/src/veins/modules/mobility/traci/TraCIRegionOfInterest.h, lib/veins/src/veins/modules/mobility/traci/TraCILauncher.h, lib/veins/src/veins/modules/mobility/traci/TraCIBuffer.h, lib/veins/src/veins/modules/mobility/traci/TraCICommandInterface.h, lib/veins/src/veins/modules/mobility/traci/TraCICoordinateTransformation.h, lib/veins/src/veins/modules/mobility/traci/TraCIConnection.h, lib/veins/src/veins/modules/mobility/traci/ParBuffer.h, lib/veins/src/veins/modules/mobility/traci/VehicleSignal.h, lib/veins/src/veins/modules/mobility/traci/TraCICoord.h, lib/veins/src/veins/modules/mobility/traci/TraCIScenarioManagerLaunchd.h, lib/veins/src/veins/modules/mobility/traci/TraCIColor.h, lib/veins/src/veins/modules/mobility/traci/TraCIScreenRecorder.h
    output: lib/veins/src/Makefile
    jobid: 3
    resources: tmpdir=/tmp

Creating Makefile in /home/dlsystem/serpentine-env/lib/veins/src...
[Wed Mar  9 02:26:05 2022]
Finished job 3.
1 of 8 steps (12%) done
Select jobs to execute...

[Wed Mar  9 02:26:05 2022]
rule build_veins:
    input: lib/veins/src/Makefile
    output: lib/veins/src/libveins_dbg.so
    jobid: 2
    wildcards: dbg=_dbg
    threads: 24
    resources: tmpdir=/tmp

make: Entering directory '/home/dlsystem/serpentine-env/lib/veins/src'
veins/base/connectionManager/BaseConnectionManager.cc
veins/base/connectionManager/ChannelAccess.cc
veins/base/connectionManager/ConnectionManager.cc
veins/base/connectionManager/NicEntryDebug.cc
veins/base/connectionManager/NicEntryDirect.cc
veins/base/modules/BaseApplLayer.cc
veins/base/modules/BaseBattery.cc
veins/base/modules/BaseLayer.cc
veins/base/modules/BaseMacLayer.cc
veins/base/modules/BaseMobility.cc
veins/base/modules/BaseModule.cc
veins/base/modules/BaseWorldUtility.cc
veins/base/modules/BatteryAccess.cc
veins/base/phyLayer/Antenna.cc
veins/base/phyLayer/BasePhyLayer.cc
veins/base/phyLayer/BaseDecider.cc
veins/base/phyLayer/ChannelInfo.cc
veins/base/phyLayer/Decider.cc
veins/base/phyLayer/PhyUtils.cc
veins/base/toolbox/Signal.cc
veins/base/toolbox/SignalUtils.cc
veins/base/toolbox/Spectrum.cc
veins/base/utils/Coord.cc
veins/base/utils/Heading.cc
In file included from ./veins/base/connectionManager/ConnectionManager.h:27,
                 from veins/base/connectionManager/ConnectionManager.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/connectionManager/ChannelAccess.h:33,
                 from veins/base/connectionManager/ChannelAccess.cc:29:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/connectionManager/BaseConnectionManager.h:27,
                 from veins/base/connectionManager/BaseConnectionManager.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseLayer.h:30,
                 from veins/base/modules/BaseLayer.cc:28:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/connectionManager/NicEntry.h:32,
                 from ./veins/base/connectionManager/NicEntryDirect.h:30,
                 from veins/base/connectionManager/NicEntryDirect.cc:28:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/connectionManager/NicEntry.h:32,
                 from ./veins/base/connectionManager/NicEntryDebug.h:30,
                 from veins/base/connectionManager/NicEntryDebug.cc:28:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseModule.h:31,
                 from veins/base/modules/BaseModule.cc:27:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BatteryAccess.h:34,
                 from veins/base/modules/BatteryAccess.cc:32:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseMacLayer.h:30,
                 from veins/base/modules/BaseMacLayer.cc:28:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/phyLayer/Decider.h:27,
                 from veins/base/phyLayer/Decider.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/utils/Coord.h:28,
                 from ./veins/base/phyLayer/Antenna.h:25,
                 from veins/base/phyLayer/Antenna.cc:23:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseBattery.h:27,
                 from veins/base/modules/BaseBattery.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseMobility.h:29,
                 from veins/base/modules/BaseMobility.cc:27:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseApplLayer.h:30,
                 from veins/base/modules/BaseApplLayer.cc:28:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/utils/Heading.h:25,
                 from veins/base/utils/Heading.cc:23:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/phyLayer/PhyUtils.h:30,
                 from veins/base/phyLayer/PhyUtils.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/toolbox/Signal.h:25,
                 from veins/base/toolbox/Signal.cc:23:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/phyLayer/BaseDecider.h:34,
                 from veins/base/phyLayer/BaseDecider.cc:32:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/phyLayer/BasePhyLayer.h:32,
                 from veins/base/phyLayer/BasePhyLayer.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/phyLayer/ChannelInfo.h:29,
                 from veins/base/phyLayer/ChannelInfo.cc:25:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/modules/BaseWorldUtility.h:29,
                 from veins/base/modules/BaseWorldUtility.cc:27:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/utils/Coord.h:28,
                 from veins/base/utils/Coord.cc:26:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/toolbox/SignalUtils.h:31,
                 from veins/base/toolbox/SignalUtils.cc:23:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
In file included from ./veins/base/toolbox/Spectrum.h:34,
                 from veins/base/toolbox/Spectrum.cc:23:
./veins/veins.h:72:26: error: ‘make_unique’ in namespace ‘std’ does not name a type
   72 | using make_unique = std::make_unique;
      |                          ^~~~~~~~~~~
veins/base/phyLayer/BaseDecider.cc: In member function ‘virtual omnetpp::simtime_t veins::BaseDecider::processUnknownSignal(veins::AirFrame*)’:
veins/base/phyLayer/BaseDecider.cc:101:66: warning: format ‘%d’ expects argument of type ‘int’, but argument 3 has type ‘long int’ [-Wformat=]
  101 |     throw cRuntimeError("Unknown state for the AirFrame with ID %d", frame->getId());
      |                                                                 ~^   ~~~~~~~~~~~~~~
      |                                                                  |               |
      |                                                                  int             long int
      |                                                                 %ld
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/Decider.o] Error 1
make: *** Waiting for unfinished jobs....
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseBattery.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/Antenna.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseModule.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseLayer.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BatteryAccess.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/utils/Heading.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/utils/Coord.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseApplLayer.o] Error 1
veins/base/phyLayer/BasePhyLayer.cc: In member function ‘virtual void veins::BasePhyLayer::handleAirFrame(veins::AirFrame*)’:
veins/base/phyLayer/BasePhyLayer.cc:419:55: warning: format ‘%s’ expects argument of type ‘char*’, but argument 3 has type ‘int’ [-Wformat=]
  419 |         throw cRuntimeError("Unknown AirFrame state: %s", frame->getState());
      |                                                      ~^   ~~~~~~~~~~~~~~~~~
      |                                                       |                  |
      |                                                       char*              int
      |                                                      %d
veins/base/phyLayer/BasePhyLayer.cc: In member function ‘virtual std::unique_ptr<veins::AirFrame> veins::BasePhyLayer::createAirFrame(omnetpp::cPacket*)’:
veins/base/phyLayer/BasePhyLayer.cc:542:12: error: ‘make_unique’ was not declared in this scope; did you mean ‘std::make_unique’?
  542 |     return make_unique<AirFrame>(macPkt->getName(), AIR_FRAME);
      |            ^~~~~~~~~~~
      |            std::make_unique
In file included from /usr/include/c++/9/memory:80,
                 from ./veins/base/phyLayer/BasePhyLayer.h:30,
                 from veins/base/phyLayer/BasePhyLayer.cc:25:
/usr/include/c++/9/bits/unique_ptr.h:868:5: note: ‘std::make_unique’ declared here
  868 |     make_unique(_Args&&...) = delete;
      |     ^~~~~~~~~~~
veins/base/phyLayer/BasePhyLayer.cc:542:32: error: expected primary-expression before ‘>’ token
  542 |     return make_unique<AirFrame>(macPkt->getName(), AIR_FRAME);
      |                                ^
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseMobility.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseMacLayer.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/connectionManager/NicEntryDirect.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/modules/BaseWorldUtility.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/connectionManager/NicEntryDebug.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/toolbox/Spectrum.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/BaseDecider.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/connectionManager/ConnectionManager.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/PhyUtils.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/connectionManager/ChannelAccess.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/toolbox/Signal.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/toolbox/SignalUtils.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/ChannelInfo.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/connectionManager/BaseConnectionManager.o] Error 1
make: *** [Makefile:210: ../out/gcc-debug/src/veins/base/phyLayer/BasePhyLayer.o] Error 1
make: Leaving directory '/home/dlsystem/serpentine-env/lib/veins/src'
[Wed Mar  9 02:26:07 2022]
Error in rule build_veins:
    jobid: 2
    output: lib/veins/src/libveins_dbg.so
    shell:
        make -j24 -C lib/veins/src MODE=debug
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
The input used to generate one or several output files has changed:
    To inspect which output files have changes, run 'snakemake --list-input-changes'.
    To trigger a re-run, use 'snakemake -R $(snakemake --list-input-changes)'.
Complete log: /home/dlsystem/serpentine-env/.snakemake/log/2022-03-09T022605.762192.snakemake.log

**Comment by mxsrc** [comment]
Can you try replacing
```
using make_unique = std::make_unique;
```
with
```
using std::make_unique;
```
in `veins.h`?

**Comment by Anas-1998** [comment]
It worked. much thanks!

**Comment by dbuse** [comment]
We upgraded the version of Veins bundled in this repository to 5.2. This should apply the patch mentioned by @mightyCelu implicitly and thus fix this issue inherently. Please let us know if the error persists.
