### ISSUE TITLE
After snakemake -jall, there are a lot of errors, 

### ISSUE THREAD

**Issue by together99** [tkn-tub/serpentine-env#5]
/usr/include/google/protobuf/wire_format_lite_inl.h:138:3: error: ‘uint32’ was not declared in this scope; did you mean ‘uint128’?
  138 |   uint32 temp;
      |   ^~~~~~
      |   uint128
/usr/include/google/protobuf/wire_format_lite_inl.h:139:35: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  139 |   if (!input->ReadLittleEndian32(&temp)) return false;
      |                                   ^~~~
      |                                   tm
/usr/include/google/protobuf/wire_format_lite_inl.h:140:24: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  140 |   *value = DecodeFloat(temp);
      |                        ^~~~
      |                        tm
/usr/include/google/protobuf/wire_format_lite_inl.h: In static member function ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = double; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = google::protobuf::internal::WireFormatLite::TYPE_DOUBLE]’:
/usr/include/google/protobuf/wire_format_lite_inl.h:147:3: error: ‘uint64’ was not declared in this scope; did you mean ‘uint’?
  147 |   uint64 temp;
      |   ^~~~~~
      |   uint
/usr/include/google/protobuf/wire_format_lite_inl.h:148:35: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  148 |   if (!input->ReadLittleEndian64(&temp)) return false;
      |                                   ^~~~
      |                                   tm
/usr/include/google/protobuf/wire_format_lite_inl.h:149:25: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  149 |   *value = DecodeDouble(temp);
      |                         ^~~~
      |                         tm
/usr/include/google/protobuf/wire_format_lite_inl.h: In static member function ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = bool; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = google::protobuf::internal::WireFormatLite::TYPE_BOOL]’:
/usr/include/google/protobuf/wire_format_lite_inl.h:156:3: error: ‘uint64’ was not declared in this scope; did you mean ‘uint’?
  156 |   uint64 temp;
      |   ^~~~~~
      |   uint
/usr/include/google/protobuf/wire_format_lite_inl.h:157:29: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  157 |   if (!input->ReadVarint64(&temp)) return false;
      |                             ^~~~
      |                             tm
/usr/include/google/protobuf/wire_format_lite_inl.h:158:12: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  158 |   *value = temp != 0;
      |            ^~~~
      |            tm
/usr/include/google/protobuf/wire_format_lite_inl.h: In static member function ‘static bool google::protobuf::internal::WireFormatLite::ReadPrimitive(google::protobuf::io::CodedInputStream*, CType*) [with CType = int; google::protobuf::internal::WireFormatLite::FieldType DeclaredType = google::protobuf::internal::WireFormatLite::TYPE_ENUM]’:
/usr/include/google/protobuf/wire_format_lite_inl.h:165:3: error: ‘uint32’ was not declared in this scope; did you mean ‘uint128’?
  165 |   uint32 temp;
      |   ^~~~~~
      |   uint128
/usr/include/google/protobuf/wire_format_lite_inl.h:166:29: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  166 |   if (!input->ReadVarint32(&temp)) return false;
      |                             ^~~~
      |                             tm
/usr/include/google/protobuf/wire_format_lite_inl.h:167:29: error: ‘temp’ was not declared in this scope; did you mean ‘tm’?
  167 |   *value = static_cast<int>(temp);
      |                             ^~~~
      |                             tm
/usr/include/google/protobuf/wire_format_lite_inl.h: At global scope:
/usr/include/google/protobuf/wire_format_lite_inl.h:172:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  172 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:179:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  179 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:186:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  186 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:196:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  196 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:206:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  206 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:216:14: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  216 | inline const uint8* WireFormatLite::ReadPrimitiveFromArray<
      |              ^~~~~
      |              uint
/usr/include/google/protobuf/wire_format_lite_inl.h:229:5: error: ‘uint32’ has not been declared
  229 |     uint32 tag,
      |     ^~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:247:5: error: ‘uint32’ has not been declared
  247 |     uint32 tag,
      |     ^~~~~~
In file included from /usr/include/google/protobuf/stubs/common.h:51,
                 from ./protobuf/veinsgym.pb.h:9,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite_inl.h: In static member function ‘static bool google::protobuf::internal::WireFormatLite::ReadRepeatedFixedSizePrimitive(int, int, google::protobuf::io::CodedInputStream*, google::protobuf::RepeatedField<Element>*)’:
/usr/include/google/protobuf/wire_format_lite_inl.h:250:3: error: there are no arguments to ‘UInt32Size’ that depend on a template parameter, so a declaration of ‘UInt32Size’ must be available [-fpermissive]
  250 |   GOOGLE_DCHECK_EQ(UInt32Size(tag), static_cast<size_t>(tag_size));
      |   ^~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:250:3: error: ‘size_t’ does not name a type
  250 |   GOOGLE_DCHECK_EQ(UInt32Size(tag), static_cast<size_t>(tag_size));
      |   ^~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite_inl.h:46:1: note: ‘size_t’ is defined in header ‘<cstddef>’; did you forget to ‘#include <cstddef>’?
   45 | #include <google/protobuf/wire_format_lite.h>
  +++ |+#include <cstddef>
   46 | #include <google/protobuf/io/coded_stream.h>
/usr/include/google/protobuf/wire_format_lite_inl.h:269:11: error: ‘uint8’ does not name a type; did you mean ‘uint’?
  269 |     const uint8* buffer = reinterpret_cast<const uint8*>(void_pointer);
      |           ^~~~~
      |           uint
/usr/include/google/protobuf/wire_format_lite_inl.h:278:13: error: ‘buffer’ was not declared in this scope; did you mean ‘zmq::buffer’?
  278 |            (buffer = io::CodedInputStream::ExpectTagFromArray(
      |             ^~~~~~
      |             zmq::buffer
In file included from ./serpentine/GymConnection.h:25,
                 from serpentine/GymConnection.cc:23:
../lib/zmq/src/zmq/zmq.hpp:1082:14: note: ‘zmq::buffer’ declared here
 1082 | const_buffer buffer(const std::basic_string<T, Traits, Allocator> &data,
      |              ^~~~~~
In file included from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite_inl.h:278:44: error: ‘ExpectTagFromArray’ is not a member of ‘google::protobuf::io::CodedInputStream’
  278 |            (buffer = io::CodedInputStream::ExpectTagFromArray(
      |                                            ^~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:280:16: error: ‘ReadPrimitiveFromArray’ was not declared in this scope
  280 |       buffer = ReadPrimitiveFromArray<CType, DeclaredType>(buffer, &value);
      |                ^~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:280:44: error: expected primary-expression before ‘,’ token
  280 |       buffer = ReadPrimitiveFromArray<CType, DeclaredType>(buffer, &value);
      |                                            ^
/usr/include/google/protobuf/wire_format_lite_inl.h: At global scope:
/usr/include/google/protobuf/wire_format_lite_inl.h:307:1: error: ‘uint32’ was not declared in this scope; did you mean ‘uint128’?
  307 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:307:1: error: ‘uint32’ has not been declared
  307 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:307:1: error: ‘uint32’ was not declared in this scope; did you mean ‘uint128’?
  307 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:307:1: error: template argument 1 is invalid
  307 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:307:1: error: template-id ‘ReadRepeatedPrimitive<<expression error>, google::protobuf::internal::WireFormatLite::TYPE_FIXED32>’ for ‘bool google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive(int, int, google::protobuf::io::CodedInputStream*, int*)’ does not match any template declaration
  307 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint32, TYPE_FIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/wire_format_lite_inl.h:45,
                 from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite.h:283:19: note: candidate is: ‘template<class CType, google::protobuf::internal::WireFormatLite::FieldType DeclaredType> static bool google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive(int, int, google::protobuf::io::CodedInputStream*, google::protobuf::RepeatedField<Element>*)’
  283 |   INL static bool ReadRepeatedPrimitive(int tag_size, uint32 tag,
      |                   ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite_inl.h:308:1: error: ‘uint64’ was not declared in this scope; did you mean ‘uint’?
  308 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint64, TYPE_FIXED64)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:308:1: error: ‘uint32’ has not been declared
  308 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint64, TYPE_FIXED64)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:308:1: error: ‘uint64’ was not declared in this scope; did you mean ‘uint’?
  308 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint64, TYPE_FIXED64)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:308:1: error: template argument 1 is invalid
  308 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint64, TYPE_FIXED64)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:308:1: error: template-id ‘ReadRepeatedPrimitive<<expression error>, google::protobuf::internal::WireFormatLite::TYPE_FIXED64>’ for ‘bool google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive(int, int, google::protobuf::io::CodedInputStream*, int*)’ does not match any template declaration
  308 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(uint64, TYPE_FIXED64)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/wire_format_lite_inl.h:45,
                 from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite.h:283:19: note: candidate is: ‘template<class CType, google::protobuf::internal::WireFormatLite::FieldType DeclaredType> static bool google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive(int, int, google::protobuf::io::CodedInputStream*, google::protobuf::RepeatedField<Element>*)’
  283 |   INL static bool ReadRepeatedPrimitive(int tag_size, uint32 tag,
      |                   ^~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/map_type_handler.h:35,
                 from /usr/include/google/protobuf/map.h:49,
                 from /usr/include/google/protobuf/generated_message_table_driven.h:34,
                 from ./protobuf/veinsgym.pb.h:25,
                 from ./serpentine/GymConnection.h:27,
                 from serpentine/GymConnection.cc:23:
/usr/include/google/protobuf/wire_format_lite_inl.h:309:1: error: ‘int32’ was not declared in this scope; did you mean ‘rintf32’?
  309 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(int32, TYPE_SFIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:309:1: error: ‘uint32’ has not been declared
  309 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(int32, TYPE_SFIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:309:1: error: ‘int32’ was not declared in this scope; did you mean ‘rintf32’?
  309 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(int32, TYPE_SFIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:309:1: error: template argument 1 is invalid
  309 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(int32, TYPE_SFIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/include/google/protobuf/wire_format_lite_inl.h:309:1: error: template-id ‘ReadRepeatedPrimitive<<expression error>, google::protobuf::internal::WireFormatLite::TYPE_SFIXED32>’ for ‘bool google::protobuf::internal::WireFormatLite::ReadRepeatedPrimitive(int, int, google::protobuf::io::CodedInputStream*, int*)’ does not match any template declaration
  309 | READ_REPEATED_FIXED_SIZE_PRIMITIVE(int32, TYPE_SFIXED32)
      | ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/google/protobuf/wire_format_lite_inl.h:45,
                 from /usr/include/google/protobuf/map_type_handler.h:35,

**Comment by dbuse** [comment]
Hi @together99, have you tried [re-generating the protobuf-c++ files](https://github.com/tkn-tub/veins-gym#protobuf-files-out-of-sync)?

**Comment by together99** [comment]
Maybe I made a mistake before. I tried it again and it's working fine now. Thank you very much! @dbuse
