### ISSUE TITLE
ZmQ error

### ISSUE THREAD

**Issue by serapergun** [tkn-tub/serpentine-env#7]
I am getting this error;

terminate called after throwing an instance of 'zmq::error_t'
  what():  Socket operation on non-socket

The communication between simulator was fine before.
I got the mean reward.
But I could not start again.

What should I do?

**Comment by dbuse** [comment]
Hi @serapergun 

I'm afraid I cannot help you with only the information provided. It sounds like the tcp socket used by the ZMQ socket got closed/destroyed for some reason. But that's all I can tell.

Please provide some detailed description of your setup and observations. For example (but not limited to):

* Did you modify the code?
* Are you using docker?
* Has the complete example run before?

**Comment by serapergun** [comment]
No, I just modified codes on jupyter notebook about training part of agent.
I deleted the serpentine-env, imported again.
It is fixed for some what that I do not understand.
Thank you.
