### ISSUE TITLE
AssertionError: Observation space (None) does not inherit from gym.spaces.Space

### ISSUE THREAD

**Issue by nazisu2020** [tkn-tub/serpentine-env#9]
Hi,
Excuse me, in the process of running the Serpentine tutorial, when I implement ```env = gym.make("veins-v1")```, I encountered the following problem: 
```
AssertionError                            Traceback (most recent call last)
/home/na/workspace/veinsv2rsu/rl_portion/serpentine-env/examples/Tutorial_Using_the_Serpentine_Scenario.ipynb Cell 9' in <cell line: 1>()
----> [1](vscode-notebook-cell:/home/na/workspace/veinsv2rsu/rl_portion/serpentine-env/examples/Tutorial_Using_the_Serpentine_Scenario.ipynb#ch0000008?line=0) env = gym.make("veins-v1")

File ~/.conda/envs/veins/lib/python3.9/site-packages/gym/envs/registration.py:601, in make(id, max_episode_steps, autoreset, disable_env_checker, **kwargs)
    599 # Run the environment checker as the lowest level wrapper
    600 if disable_env_checker is False:
--> 601     env = PassiveEnvChecker(env)
    603 # Add the order enforcing wrapper
    604 if spec_.order_enforce:

File ~/.conda/envs/veins/lib/python3.9/site-packages/gym/wrappers/env_checker.py:25, in PassiveEnvChecker.__init__(self, env)
     20 super().__init__(env)
     22 assert hasattr(
     23     env, "action_space"
     24 ), "You must specify a action space. https://www.gymlibrary.ml/content/environment_creation/"
---> 25 check_observation_space(env.action_space)
     26 assert hasattr(
     27     env, "observation_space"
     28 ), "You must specify an observation space. https://www.gymlibrary.ml/content/environment_creation/"
     29 check_action_space(env.observation_space)

File ~/.conda/envs/veins/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:144, in check_observation_space(observation_space)
    142 """A passive check of the environment observation space that should not affect the environment."""
...
    148 elif isinstance(observation_space, spaces.Box):
    149     # Check if the box is an image (shape is 3 elements and the last element is 1 or 3)
    150     _check_box_observation_space(observation_space)

AssertionError: Observation space (None) does not inherit from gym.spaces.Space
```
I have no idea to change the Observation space in this example. Could you tell me how to solve this problem? Thank you very much!!

**Comment by dbuse** [comment]
Hi @nazisu2020,

the observation space is defined via `*.gym_connection.observation_space` in the [omnetpp.ini file](https://github.com/tkn-tub/serpentine-env/blob/master/scenario/omnetpp.ini#L130) and transmitted to the `env` object when the Veins/OMNeT++ simulation connects to it. This way, the definition only depends on the scenario/environment and the `veins-gym` library can stay agnostic.

I guess you have changed or removed this parameter somehow...

Best,
Dominik

**Comment by nazisu2020** [comment]
Hi @dbuse ,
 
Thanks for your quick reply, firstly.

But there is no changed in this [tutorial ipynb file](https://github.com/tkn-tub/serpentine-env/blob/master/examples/Tutorial_Using_the_Serpentine_Scenario.ipynb), I just via ```git clone https://github.com/tkn-tub/serpentine-env``` put this code into VsCode and via _Jupyter Extension for Visual Studio Code_ to run this .ipynb file.

Maybe if it has something to do with the version of omnet++/veins/protoc/sumo... I use?

**Comment by dbuse** [comment]
That is strange. Does the same error appear if you run the [random agent script](https://github.com/tkn-tub/serpentine-env/blob/master/examples/random_agent.py) instead of the Jupyter notebook?

You could also try to [enable debug output of Veins](https://github.com/tkn-tub/veins-gym#showing-the-debug-output-of-veins-through-the-agent) or run Veins separately to see if there is any error when starting Veins.

**Comment by dbuse** [comment]
Please update VeinsGym to 0.3.3+ and seee if the error persists. Also see #8.

**Comment by nazisu2020** [comment]
Hi @dbuse  ,
Thanks for your advices!

I will try based on your suggestion.

**Comment by nazisu2020** [comment]
Hi @dbuse 
After I update VeinsGym to the new 0.3.3 version, I can run this tutorial example,
Thank you very much!!

But there is a UserWarning in the process of running ```env.reset()```, which should not affect it, right?
```bash
(veins) na@na-Precision-5820-Tower:~/workspace/serpentine-env$ /home/na/.conda/envs/veins/bin/python /home/na/workspace/serpentine-env/examples/random_agent.py
/home/na/.conda/envs/veins/lib/python3.9/site-packages/gym/utils/passive_env_checker.py:223: UserWarning: WARN: The default seed argument in `Env.reset` should be `None`, otherwise the environment will by default always be deterministic
  logger.warn(
Number of steps taken: 3680
Mean reward: 0.6732228221518555
```

**Comment by dbuse** [comment]
Yeah, that is only relevant for future interfaces. Happy I could help.
